#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v4
# autospec commit: da8b975
#
Name     : qt6speech
Version  : 6.6.2
Release  : 7
URL      : https://download.qt.io/official_releases/qt/6.6/6.6.2/submodules/qtspeech-everywhere-src-6.6.2.tar.xz
Source0  : https://download.qt.io/official_releases/qt/6.6/6.6.2/submodules/qtspeech-everywhere-src-6.6.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qt6speech-lib = %{version}-%{release}
Requires: qt6speech-license = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : mesa-dev
BuildRequires : pkg-config
BuildRequires : qt6base-dev
BuildRequires : qt6declarative-dev
BuildRequires : qt6multimedia-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the qt6speech package.
Group: Development
Requires: qt6speech-lib = %{version}-%{release}
Provides: qt6speech-devel = %{version}-%{release}
Requires: qt6speech = %{version}-%{release}

%description dev
dev components for the qt6speech package.


%package lib
Summary: lib components for the qt6speech package.
Group: Libraries
Requires: qt6speech-license = %{version}-%{release}

%description lib
lib components for the qt6speech package.


%package license
Summary: license components for the qt6speech package.
Group: Default

%description license
license components for the qt6speech package.


%prep
%setup -q -n qtspeech-everywhere-src-6.6.2
cd %{_builddir}/qtspeech-everywhere-src-6.6.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707943601
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..
make  %{?_smp_mflags}
popd
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707943601
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qt6speech
cp %{_builddir}/qtspeech-everywhere-src-%{version}/LICENSES/BSD-3-Clause.txt %{buildroot}/usr/share/package-licenses/qt6speech/b073f11f0c81a95ab5e32aa6b5d23a5955a95274 || :
cp %{_builddir}/qtspeech-everywhere-src-%{version}/LICENSES/GFDL-1.3-no-invariants-only.txt %{buildroot}/usr/share/package-licenses/qt6speech/715f995f11805ee85601834220c43b082f457ea3 || :
cp %{_builddir}/qtspeech-everywhere-src-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/qt6speech/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qtspeech-everywhere-src-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6speech/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qtspeech-everywhere-src-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/qt6speech/f45ee1c765646813b442ca58de72e20a64a7ddba || :
export GOAMD64=v2
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/qt6/metatypes/qt6texttospeech_relwithdebinfo_metatypes.json
/usr/lib64/qt6/mkspecs/modules/qt_lib_texttospeech.pri
/usr/lib64/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri
/usr/lib64/qt6/modules/TextToSpeech.json
/usr/lib64/qt6/qml/QtTextToSpeech/plugins.qmltypes
/usr/lib64/qt6/qml/QtTextToSpeech/qmldir

%files dev
%defattr(-,root,root,-)
/usr/include/QtTextToSpeech/6.6.2/QtTextToSpeech/private/qtexttospeech_p.h
/usr/include/QtTextToSpeech/6.6.2/QtTextToSpeech/private/qttexttospeech-config_p.h
/usr/include/QtTextToSpeech/6.6.2/QtTextToSpeech/private/qvoice_p.h
/usr/include/QtTextToSpeech/QTextToSpeech
/usr/include/QtTextToSpeech/QTextToSpeechEngine
/usr/include/QtTextToSpeech/QTextToSpeechPlugin
/usr/include/QtTextToSpeech/QVoice
/usr/include/QtTextToSpeech/QtTextToSpeech
/usr/include/QtTextToSpeech/QtTextToSpeechDepends
/usr/include/QtTextToSpeech/QtTextToSpeechVersion
/usr/include/QtTextToSpeech/qtexttospeech.h
/usr/include/QtTextToSpeech/qtexttospeech_global.h
/usr/include/QtTextToSpeech/qtexttospeechengine.h
/usr/include/QtTextToSpeech/qtexttospeechplugin.h
/usr/include/QtTextToSpeech/qttexttospeech-config.h
/usr/include/QtTextToSpeech/qttexttospeechversion.h
/usr/include/QtTextToSpeech/qvoice.h
/usr/lib64/cmake/Qt6/FindFlite.cmake
/usr/lib64/cmake/Qt6/FindSpeechDispatcher.cmake
/usr/lib64/cmake/Qt6BuildInternals/StandaloneTests/QtSpeechTestsConfig.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlConfig.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlConfigVersion.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6Qml/QmlPlugins/Qt6TextToSpeechQmlTargets.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginConfig.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginConfigVersion.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6QTextToSpeechMockPluginTargets.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechAdditionalTargetInfo.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechConfig.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechConfigVersion.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechConfigVersionImpl.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechDependencies.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechPlugins.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechTargets-relwithdebinfo.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechTargets.cmake
/usr/lib64/cmake/Qt6TextToSpeech/Qt6TextToSpeechVersionlessTargets.cmake
/usr/lib64/libQt6TextToSpeech.prl
/usr/lib64/libQt6TextToSpeech.so
/usr/lib64/pkgconfig/Qt6TextToSpeech.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libQt6TextToSpeech.so.6.6.2
/V3/usr/lib64/qt6/plugins/texttospeech/libqtexttospeech_mock.so
/V3/usr/lib64/qt6/qml/QtTextToSpeech/libtexttospeechqmlplugin.so
/usr/lib64/libQt6TextToSpeech.so.6
/usr/lib64/libQt6TextToSpeech.so.6.6.2
/usr/lib64/qt6/plugins/texttospeech/libqtexttospeech_mock.so
/usr/lib64/qt6/qml/QtTextToSpeech/libtexttospeechqmlplugin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qt6speech/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qt6speech/715f995f11805ee85601834220c43b082f457ea3
/usr/share/package-licenses/qt6speech/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qt6speech/b073f11f0c81a95ab5e32aa6b5d23a5955a95274
/usr/share/package-licenses/qt6speech/f45ee1c765646813b442ca58de72e20a64a7ddba
